name: Android Build

on:
  push:
    branches:
      - master  # Change this to your main branch name (e.g., master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '12'  # Change this to the required Java version for your Android project

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug  # Change 'assembleDebug' to 'assembleRelease' if you want a release build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug  # Change this to your desired artifact name
          path: app/build/outputs/apk/debug/app-debug.apk  # Change the path to the location of your APK file
