name: Android Build

on:
  push:
    branches:
      - master  # Change this to your main branch name (e.g., master)
      - development

jobs:
  build-debug:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'  # Change this to the required Java version for your Android project

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.2.0
        with:
          ndk-version: r14b

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug  # Change 'assembleDebug' to 'assembleRelease' if you want a release build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: SENDA-development  # Change this to your desired artifact name
          path: app/build/outputs/apk/debug/app-debug.apk  # Change the path to the location of your APK file

  build-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'  # Change this to the required Java version for your Android project

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.2.0
        with:
          ndk-version: r14b

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease  # Change 'assembleDebug' to 'assembleRelease' if you want a release build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: SENDA-master  # Change this to your desired artifact name
          path: app/build/outputs/apk/release/app-release-unsigned.apk  # Change the path to the location of your APK file
